//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Just_Do_It_12_Rabbit_Explosion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabbit
    {
        public int RabbitID { get; set; }
        public Nullable<int> Age { get; set; }
        public string Name { get; set; }
    }
}
